[tool.poetry]
name = "connect 4"
version = "0.1.0"
description = ""
authors = ["Vladimir Moroz <vladimir.moroz.a@yandex.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
